//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculator.Win {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CalculatorWinResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CalculatorWinResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Calculator.Win.CalculatorWinResource", typeof(CalculatorWinResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ).
        /// </summary>
        internal static string CloseBrace {
            get {
                return ResourceManager.GetString("CloseBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consolas.
        /// </summary>
        internal static string Consolas {
            get {
                return ResourceManager.GetString("Consolas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cos.
        /// </summary>
        internal static string Cosine {
            get {
                return ResourceManager.GetString("Cosine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception is .
        /// </summary>
        internal static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fntConsolas.
        /// </summary>
        internal static string fntConsolas {
            get {
                return ResourceManager.GetString("fntConsolas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fntConsolasBold.
        /// </summary>
        internal static string fntConsolasBold {
            get {
                return ResourceManager.GetString("fntConsolasBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log.
        /// </summary>
        internal static string Log10 {
            get {
                return ResourceManager.GetString("Log10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ln.
        /// </summary>
        internal static string LogE {
            get {
                return ResourceManager.GetString("LogE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --.
        /// </summary>
        internal static string MinusMinus {
            get {
                return ResourceManager.GetString("MinusMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string minusSign {
            get {
                return ResourceManager.GetString("minusSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (.
        /// </summary>
        internal static string OpenBrace {
            get {
                return ResourceManager.GetString("OpenBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        internal static string Plus {
            get {
                return ResourceManager.GetString("Plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +-.
        /// </summary>
        internal static string PlusMinus {
            get {
                return ResourceManager.GetString("PlusMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string Point {
            get {
                return ResourceManager.GetString("Point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sin.
        /// </summary>
        internal static string Sine {
            get {
                return ResourceManager.GetString("Sine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tan.
        /// </summary>
        internal static string Tangent {
            get {
                return ResourceManager.GetString("Tangent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value.
        /// </summary>
        internal static string value {
            get {
                return ResourceManager.GetString("value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the sign 
        ///negative to postive or postive to negative
        ///Press Shift+1 from keyborard!!.
        /// </summary>
        internal static string value___ {
            get {
                return ResourceManager.GetString("value+/-", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press 0 from Keyboard!!.
        /// </summary>
        internal static string value0 {
            get {
                return ResourceManager.GetString("value0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press 1 from Keyboard!!.
        /// </summary>
        internal static string value1 {
            get {
                return ResourceManager.GetString("value1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate the Reciprocal of value
        ///Press &apos;Shift+/&apos; from keyborard!!.
        /// </summary>
        internal static string value1_x {
            get {
                return ResourceManager.GetString("value1/x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press 2 from Keyboard!!.
        /// </summary>
        internal static string value2 {
            get {
                return ResourceManager.GetString("value2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press 3 from Keyboard!!.
        /// </summary>
        internal static string value3 {
            get {
                return ResourceManager.GetString("value3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press 4 from Keyboard!!.
        /// </summary>
        internal static string value4 {
            get {
                return ResourceManager.GetString("value4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press 5 from Keyboard!!.
        /// </summary>
        internal static string value5 {
            get {
                return ResourceManager.GetString("value5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press 6 from Keyboard!!.
        /// </summary>
        internal static string value6 {
            get {
                return ResourceManager.GetString("value6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press 7 from Keyboard!!.
        /// </summary>
        internal static string value7 {
            get {
                return ResourceManager.GetString("value7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press 8 from Keyboard!!.
        /// </summary>
        internal static string value8 {
            get {
                return ResourceManager.GetString("value8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press 9 from Keyboard!!.
        /// </summary>
        internal static string value9 {
            get {
                return ResourceManager.GetString("value9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clears the Whole expression
        ///Press &apos;B&apos; from keyborard!!.
        /// </summary>
        internal static string valueAC {
            get {
                return ResourceManager.GetString("valueAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the one char from value
        ///Press backsapce from keyborard!!.
        /// </summary>
        internal static string valueC {
            get {
                return ResourceManager.GetString("valueC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clears the Entry
        ///Press &apos;c&apos; from keyborard!!.
        /// </summary>
        internal static string valueCE {
            get {
                return ResourceManager.GetString("valueCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate cos(value)
        ///Press Shift+5 from keyborard!!.
        /// </summary>
        internal static string valuecos {
            get {
                return ResourceManager.GetString("valuecos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate ln(value)
        ///Press L  from keyborard!!.
        /// </summary>
        internal static string valueln {
            get {
                return ResourceManager.GetString("valueln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate Log10(value)
        ///Press l from keyborard!!.
        /// </summary>
        internal static string valuelog {
            get {
                return ResourceManager.GetString("valuelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the Value stored in memory
        ///Press Shift+3 from keyborard!!.
        /// </summary>
        internal static string valueMC {
            get {
                return ResourceManager.GetString("valueMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read the value from memory
        ///Press Shift+4 from keyborard!!.
        /// </summary>
        internal static string valueMR {
            get {
                return ResourceManager.GetString("valueMR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store the value in memory
        ///Press Shift+7 from keyborard!!.
        /// </summary>
        internal static string valueMS {
            get {
                return ResourceManager.GetString("valueMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate the Expression
        ///Press Enter from keyborard!!.
        /// </summary>
        internal static string valueResult {
            get {
                return ResourceManager.GetString("valueResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate sin(value)
        ///Press &apos;S&apos; from keyborard!!.
        /// </summary>
        internal static string valuesin {
            get {
                return ResourceManager.GetString("valuesin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate tan(value)
        ///Press &apos;T&apos; from keyborard!!.
        /// </summary>
        internal static string valuetan {
            get {
                return ResourceManager.GetString("valuetan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string zero {
            get {
                return ResourceManager.GetString("zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (0-.
        /// </summary>
        internal static string ZeroMinus {
            get {
                return ResourceManager.GetString("ZeroMinus", resourceCulture);
            }
        }
    }
}
