//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculator.Win {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CalculatorWinControls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CalculatorWinControls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Calculator.Win.CalculatorWinControls", typeof(CalculatorWinControls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .,38,32,2,142,307,fntConsolas.
        /// </summary>
        internal static string bntPoint {
            get {
                return ResourceManager.GetString("bntPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +,38,32,2,195,113,fntConsolas.
        /// </summary>
        internal static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;-,38,32,2,90,113,fntConsolas.
        /// </summary>
        internal static string btnBackspace {
            get {
                return ResourceManager.GetString("btnBackspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC,38,32,2,38,113,fntConsolas.
        /// </summary>
        internal static string btnClear {
            get {
                return ResourceManager.GetString("btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CE,38,32,2,142,113,fntConsolas.
        /// </summary>
        internal static string btnClearEntry {
            get {
                return ResourceManager.GetString("btnClearEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ),38,32,2,352,113,fntConsolas.
        /// </summary>
        internal static string btnCloseBracket {
            get {
                return ResourceManager.GetString("btnCloseBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cos,38,32,2,300,259,fntConsolas.
        /// </summary>
        internal static string btnCosine {
            get {
                return ResourceManager.GetString("btnCosine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /,38,32,2,195,259,fntConsolas.
        /// </summary>
        internal static string btnDivide {
            get {
                return ResourceManager.GetString("btnDivide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8,38,32,2,90,161,fntConsolasBold.
        /// </summary>
        internal static string btnEight {
            get {
                return ResourceManager.GetString("btnEight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5,38,32,2,90,210,fntConsolasBold.
        /// </summary>
        internal static string btnFive {
            get {
                return ResourceManager.GetString("btnFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4,38,32,2,38,210,fntConsolasBold.
        /// </summary>
        internal static string btnFour {
            get {
                return ResourceManager.GetString("btnFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log,38,32,2,352,307,fntConsolas.
        /// </summary>
        internal static string btnLog10 {
            get {
                return ResourceManager.GetString("btnLog10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ln,38,32,2,300,307,fntConsolas.
        /// </summary>
        internal static string btnLogE {
            get {
                return ResourceManager.GetString("btnLogE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MC,38,32,2,300,210,fntConsolas.
        /// </summary>
        internal static string btnMC {
            get {
                return ResourceManager.GetString("btnMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M-,38,32,2,300,161,fntConsolas.
        /// </summary>
        internal static string btnMminus {
            get {
                return ResourceManager.GetString("btnMminus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M+,38,32,2,248,161,fntConsolas.
        /// </summary>
        internal static string btnMplus {
            get {
                return ResourceManager.GetString("btnMplus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MR,38,32,2,352,161,fntConsolas.
        /// </summary>
        internal static string btnMR {
            get {
                return ResourceManager.GetString("btnMR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS,38,32,2,248,210,fntConsolas.
        /// </summary>
        internal static string btnMS {
            get {
                return ResourceManager.GetString("btnMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *,38,32,2,195,210,fntConsolas.
        /// </summary>
        internal static string btnMultiply {
            get {
                return ResourceManager.GetString("btnMultiply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9,38,32,2,142,161,fntConsolasBold.
        /// </summary>
        internal static string btnNine {
            get {
                return ResourceManager.GetString("btnNine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,38,32,2,38,257,fntConsolasBold.
        /// </summary>
        internal static string btnOne {
            get {
                return ResourceManager.GetString("btnOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (,38,32,2,300,113,fntConsolas.
        /// </summary>
        internal static string btnOpenBracket {
            get {
                return ResourceManager.GetString("btnOpenBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %,38,32,2,248,113,fntConsolas.
        /// </summary>
        internal static string btnPerCent {
            get {
                return ResourceManager.GetString("btnPerCent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1/x,38,32,2,352,210,fntConsolas.
        /// </summary>
        internal static string btnReciprocal {
            get {
                return ResourceManager.GetString("btnReciprocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result,92,32,2,195,307,fntConsolas.
        /// </summary>
        internal static string btnResult {
            get {
                return ResourceManager.GetString("btnResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7,38,32,2,38,161,fntConsolasBold.
        /// </summary>
        internal static string btnSeven {
            get {
                return ResourceManager.GetString("btnSeven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +/-,38,32,2,38,307,fntConsolas.
        /// </summary>
        internal static string btnSignChange {
            get {
                return ResourceManager.GetString("btnSignChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sin,38,32,2,248,259,fntConsolas.
        /// </summary>
        internal static string btnSine {
            get {
                return ResourceManager.GetString("btnSine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6,38,32,2,142,210,fntConsolasBold.
        /// </summary>
        internal static string btnSix {
            get {
                return ResourceManager.GetString("btnSix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -,38,32,2,195,161,fntConsolas.
        /// </summary>
        internal static string btnSubtract {
            get {
                return ResourceManager.GetString("btnSubtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tan,38,32,2,352,259,fntConsolas.
        /// </summary>
        internal static string btnTangent {
            get {
                return ResourceManager.GetString("btnTangent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3,38,32,2,142,257,fntConsolasBold.
        /// </summary>
        internal static string btnThree {
            get {
                return ResourceManager.GetString("btnThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2,38,32,2,90,257,fntConsolasBold.
        /// </summary>
        internal static string btnTwo {
            get {
                return ResourceManager.GetString("btnTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,38,32,2,90,307,fntConsolasBold.
        /// </summary>
        internal static string btnZero {
            get {
                return ResourceManager.GetString("btnZero", resourceCulture);
            }
        }
    }
}
