//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculator.Console {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConsoleData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConsoleData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Calculator.Console.ConsoleData", typeof(ConsoleData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ************ ADDITION (x + y) ***************.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ****************CALCULATOR****************
        ///.
        /// </summary>
        internal static string CalculatorHead {
            get {
                return ResourceManager.GetString("CalculatorHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Choice of Operation ::
        ///+    for Addition
        ///-    for Subtraction
        ///*    for Multiplication
        ////    for Division
        ///mod  for Modulus
        ///log  for Log Base 10
        ///ln   for Log Base e
        ///e^   for Exponential
        ///sqrt for Square Root
        ///^    for Power 
        ///sin  for Sine
        ///cos  for Cosine
        ///tan  for Tangent.
        /// </summary>
        internal static string Choices {
            get {
                return ResourceManager.GetString("Choices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Press 1 to continue or any other key to exit.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ************ Cosine [cos(x)] ***************.
        /// </summary>
        internal static string Cosine {
            get {
                return ResourceManager.GetString("Cosine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ************ DIVISON (x / y) ***************.
        /// </summary>
        internal static string Divide {
            get {
                return ResourceManager.GetString("Divide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ************ Exponenital [e^x] ***************.
        /// </summary>
        internal static string Exponential {
            get {
                return ResourceManager.GetString("Exponential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ************ LOGARTHIMIC BASE 10 [Log10(x)] ***************.
        /// </summary>
        internal static string Log10 {
            get {
                return ResourceManager.GetString("Log10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ************ LOGARITHMIC BASE E [Loge(x)] ***************.
        /// </summary>
        internal static string LogE {
            get {
                return ResourceManager.GetString("LogE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----Math Error----.
        /// </summary>
        internal static string MathError {
            get {
                return ResourceManager.GetString("MathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ************ MODULUS (x % y) ***************.
        /// </summary>
        internal static string Modulus {
            get {
                return ResourceManager.GetString("Modulus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ************ MULTIPLICATION (x * y) ***************.
        /// </summary>
        internal static string Multiply {
            get {
                return ResourceManager.GetString("Multiply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the non-zero Element.
        /// </summary>
        internal static string NonZero {
            get {
                return ResourceManager.GetString("NonZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string One {
            get {
                return ResourceManager.GetString("One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ************ Power [x^y] ***************.
        /// </summary>
        internal static string Power {
            get {
                return ResourceManager.GetString("Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Result is  .
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ************ Sine [sin(x)] ***************.
        /// </summary>
        internal static string Sine {
            get {
                return ResourceManager.GetString("Sine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ************ Square Root of x ***************.
        /// </summary>
        internal static string SquareRoot {
            get {
                return ResourceManager.GetString("SquareRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ************ SUBTRACTION (x - y) ***************.
        /// </summary>
        internal static string Subtract {
            get {
                return ResourceManager.GetString("Subtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ************ Tangent [tan(x)] ***************.
        /// </summary>
        internal static string Tangent {
            get {
                return ResourceManager.GetString("Tangent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OOPS Entered wrong choice !!.
        /// </summary>
        internal static string WrongChoice {
            get {
                return ResourceManager.GetString("WrongChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a number 
        ///Enter a valid Number for x ::.
        /// </summary>
        internal static string x_not_value {
            get {
                return ResourceManager.GetString("x_not_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the value of x ::.
        /// </summary>
        internal static string x_value {
            get {
                return ResourceManager.GetString("x_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a number 
        ///Enter a valid Number for y ::.
        /// </summary>
        internal static string y_not_value {
            get {
                return ResourceManager.GetString("y_not_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the value of y ::.
        /// </summary>
        internal static string y_value {
            get {
                return ResourceManager.GetString("y_value", resourceCulture);
            }
        }
    }
}
